// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "backoff_vi.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic backoff_vi::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic backoff_vi::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> backoff_vi::ap_ST_fsm_state1 = "1";
const sc_lv<32> backoff_vi::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<10> backoff_vi::ap_const_lv10_0 = "0000000000";
const sc_lv<1> backoff_vi::ap_const_lv1_0 = "0";
const sc_lv<1> backoff_vi::ap_const_lv1_1 = "1";
const sc_lv<3> backoff_vi::ap_const_lv3_3 = "11";
const sc_lv<10> backoff_vi::ap_const_lv10_3FF = "1111111111";
const bool backoff_vi::ap_const_boolean_1 = true;

backoff_vi::backoff_vi(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln221_fu_44_p2);
    sensitive << ( vi_backoff_counter );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_current_txop_holder_o);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( current_txop_holder_i );
    sensitive << ( icmp_ln212_fu_38_p2 );
    sensitive << ( icmp_ln213_fu_56_p2 );

    SC_METHOD(thread_current_txop_holder_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln212_fu_38_p2 );
    sensitive << ( icmp_ln213_fu_56_p2 );

    SC_METHOD(thread_icmp_ln212_fu_38_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( vi_backoff_counter );

    SC_METHOD(thread_icmp_ln213_fu_56_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( current_txop_holder_i );
    sensitive << ( icmp_ln212_fu_38_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    vi_backoff_counter = "0000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "backoff_vi_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, current_txop_holder_i, "(port)current_txop_holder_i");
    sc_trace(mVcdFile, current_txop_holder_o, "(port)current_txop_holder_o");
    sc_trace(mVcdFile, current_txop_holder_o_ap_vld, "(port)current_txop_holder_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, vi_backoff_counter, "vi_backoff_counter");
    sc_trace(mVcdFile, add_ln221_fu_44_p2, "add_ln221_fu_44_p2");
    sc_trace(mVcdFile, icmp_ln212_fu_38_p2, "icmp_ln212_fu_38_p2");
    sc_trace(mVcdFile, icmp_ln213_fu_56_p2, "icmp_ln213_fu_56_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("backoff_vi.hdltvin.dat");
    mHdltvoutHandle.open("backoff_vi.hdltvout.dat");
}

backoff_vi::~backoff_vi() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void backoff_vi::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln212_fu_38_p2.read(), ap_const_lv1_0))) {
        vi_backoff_counter = add_ln221_fu_44_p2.read();
    }
}

void backoff_vi::thread_add_ln221_fu_44_p2() {
    add_ln221_fu_44_p2 = (!vi_backoff_counter.read().is_01() || !ap_const_lv10_3FF.is_01())? sc_lv<10>(): (sc_biguint<10>(vi_backoff_counter.read()) + sc_bigint<10>(ap_const_lv10_3FF));
}

void backoff_vi::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void backoff_vi::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void backoff_vi::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void backoff_vi::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void backoff_vi::thread_current_txop_holder_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(icmp_ln212_fu_38_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln213_fu_56_p2.read()))) {
        current_txop_holder_o = ap_const_lv3_3;
    } else {
        current_txop_holder_o = current_txop_holder_i.read();
    }
}

void backoff_vi::thread_current_txop_holder_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(icmp_ln212_fu_38_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln213_fu_56_p2.read()))) {
        current_txop_holder_o_ap_vld = ap_const_logic_1;
    } else {
        current_txop_holder_o_ap_vld = ap_const_logic_0;
    }
}

void backoff_vi::thread_icmp_ln212_fu_38_p2() {
    icmp_ln212_fu_38_p2 = (!vi_backoff_counter.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(vi_backoff_counter.read() == ap_const_lv10_0);
}

void backoff_vi::thread_icmp_ln213_fu_56_p2() {
    icmp_ln213_fu_56_p2 = (!current_txop_holder_i.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): (sc_biguint<3>(current_txop_holder_i.read()) < sc_biguint<3>(ap_const_lv3_3));
}

void backoff_vi::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void backoff_vi::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"current_txop_holder_i\" :  \"" << current_txop_holder_i.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"current_txop_holder_o\" :  \"" << current_txop_holder_o.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"current_txop_holder_o_ap_vld\" :  \"" << current_txop_holder_o_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

