// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="send_frame,hls_ip_2019_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.016500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=18,HLS_SYN_FF=6548,HLS_SYN_LUT=15348,HLS_VERSION=2019_2}" *)

module send_frame (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        source_addr_mac_address0,
        source_addr_mac_ce0,
        source_addr_mac_q0,
        source_addr_mac_address1,
        source_addr_mac_ce1,
        source_addr_mac_q1,
        dest_addr_mac_address0,
        dest_addr_mac_ce0,
        dest_addr_mac_we0,
        dest_addr_mac_d0,
        dest_addr_mac_q0,
        dest_addr_mac_address1,
        dest_addr_mac_ce1,
        dest_addr_mac_we1,
        dest_addr_mac_d1,
        dest_addr_mac_q1,
        data_address0,
        data_ce0,
        data_q0,
        up,
        s_class,
        c_identifier_operating_class,
        c_identifier_channel_number,
        t_slot,
        d_rate,
        tx_power_lvl,
        expiry_time,
        mac_frame_address0,
        mac_frame_ce0,
        mac_frame_we0,
        mac_frame_d0,
        mac_frame_q0,
        medium_state,
        current_txop_holder_i,
        current_txop_holder_o,
        current_txop_holder_o_ap_vld,
        received_frame_address0,
        received_frame_ce0,
        received_frame_we0,
        received_frame_d0,
        received_frame_q0,
        received_frame_address1,
        received_frame_ce1,
        received_frame_we1,
        received_frame_d1,
        received_frame_q1
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] source_addr_mac_address0;
output   source_addr_mac_ce0;
input  [7:0] source_addr_mac_q0;
output  [2:0] source_addr_mac_address1;
output   source_addr_mac_ce1;
input  [7:0] source_addr_mac_q1;
output  [2:0] dest_addr_mac_address0;
output   dest_addr_mac_ce0;
output   dest_addr_mac_we0;
output  [7:0] dest_addr_mac_d0;
input  [7:0] dest_addr_mac_q0;
output  [2:0] dest_addr_mac_address1;
output   dest_addr_mac_ce1;
output   dest_addr_mac_we1;
output  [7:0] dest_addr_mac_d1;
input  [7:0] dest_addr_mac_q1;
output  [6:0] data_address0;
output   data_ce0;
input  [7:0] data_q0;
input  [3:0] up;
input  [0:0] s_class;
input  [7:0] c_identifier_operating_class;
input  [7:0] c_identifier_channel_number;
input  [1:0] t_slot;
input  [6:0] d_rate;
input  [3:0] tx_power_lvl;
input  [63:0] expiry_time;
output  [6:0] mac_frame_address0;
output   mac_frame_ce0;
output   mac_frame_we0;
output  [7:0] mac_frame_d0;
input  [7:0] mac_frame_q0;
input  [0:0] medium_state;
input  [2:0] current_txop_holder_i;
output  [2:0] current_txop_holder_o;
output   current_txop_holder_o_ap_vld;
output  [6:0] received_frame_address0;
output   received_frame_ce0;
output   received_frame_we0;
output  [7:0] received_frame_d0;
input  [7:0] received_frame_q0;
output  [6:0] received_frame_address1;
output   received_frame_ce1;
output   received_frame_we1;
output  [7:0] received_frame_d1;
input  [7:0] received_frame_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg source_addr_mac_ce0;
reg source_addr_mac_ce1;
reg data_ce0;
reg[6:0] mac_frame_address0;
reg mac_frame_ce0;
reg mac_frame_we0;
reg[7:0] mac_frame_d0;
reg[2:0] current_txop_holder_o;
reg current_txop_holder_o_ap_vld;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] available_spaces_bk;
reg   [1:0] write_pointer_bk;
reg   [2:0] available_spaces_be;
reg   [1:0] write_pointer_be;
reg   [2:0] available_spaces_vi;
reg   [1:0] write_pointer_vi;
reg   [2:0] available_spaces_vo;
reg   [1:0] write_pointer_vo;
reg   [10:0] edca_queues_address0;
reg    edca_queues_ce0;
reg    edca_queues_we0;
reg   [7:0] edca_queues_d0;
wire   [7:0] edca_queues_q0;
reg   [1:0] read_pointer_bk;
reg   [1:0] read_pointer_be;
reg   [1:0] read_pointer_vi;
reg   [1:0] read_pointer_vo;
reg   [9:0] CW_bk;
reg   [31:0] rand_state;
reg   [9:0] bk_backoff_counter;
reg   [9:0] CW_be;
reg   [9:0] be_backoff_counter;
reg   [9:0] CW_vi;
reg   [9:0] vi_backoff_counter;
reg   [9:0] vo_backoff_counter;
reg   [6:0] count;
reg   [6:0] frame_address0;
reg    frame_ce0;
reg    frame_we0;
wire   [7:0] frame_q0;
wire    ap_CS_fsm_state7;
wire   [6:0] i_fu_451_p2;
reg   [6:0] i_reg_546;
wire    ap_CS_fsm_state10;
reg   [6:0] count_load_reg_551;
wire   [0:0] icmp_ln22_fu_445_p2;
wire   [0:0] icmp_ln10_fu_461_p2;
reg   [0:0] icmp_ln10_reg_556;
wire   [6:0] q_fu_473_p2;
reg   [6:0] q_reg_563;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln12_fu_479_p1;
reg   [63:0] zext_ln12_reg_568;
wire   [0:0] icmp_ln11_fu_467_p2;
wire   [6:0] add_ln15_fu_484_p2;
reg   [6:0] add_ln15_reg_578;
wire   [0:0] icmp_ln16_fu_490_p2;
reg   [0:0] icmp_ln16_reg_584;
wire    grp_initial_edca_process_fu_240_ap_start;
wire    grp_initial_edca_process_fu_240_ap_done;
wire    grp_initial_edca_process_fu_240_ap_idle;
wire    grp_initial_edca_process_fu_240_ap_ready;
wire   [2:0] grp_initial_edca_process_fu_240_current_txop_holder_o;
wire    grp_initial_edca_process_fu_240_current_txop_holder_o_ap_vld;
wire   [6:0] grp_initial_edca_process_fu_240_frame_to_transfer_address0;
wire    grp_initial_edca_process_fu_240_frame_to_transfer_ce0;
wire    grp_initial_edca_process_fu_240_frame_to_transfer_we0;
wire   [7:0] grp_initial_edca_process_fu_240_frame_to_transfer_d0;
wire   [2:0] grp_initial_edca_process_fu_240_available_spaces_vo_o;
wire    grp_initial_edca_process_fu_240_available_spaces_vo_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_vo_backoff_counter_o;
wire    grp_initial_edca_process_fu_240_vo_backoff_counter_o_ap_vld;
wire   [31:0] grp_initial_edca_process_fu_240_rand_state_o;
wire    grp_initial_edca_process_fu_240_rand_state_o_ap_vld;
wire   [2:0] grp_initial_edca_process_fu_240_available_spaces_vi_o;
wire    grp_initial_edca_process_fu_240_available_spaces_vi_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_vi_backoff_counter_o;
wire    grp_initial_edca_process_fu_240_vi_backoff_counter_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_CW_vi_o;
wire    grp_initial_edca_process_fu_240_CW_vi_o_ap_vld;
wire   [2:0] grp_initial_edca_process_fu_240_available_spaces_be_o;
wire    grp_initial_edca_process_fu_240_available_spaces_be_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_be_backoff_counter_o;
wire    grp_initial_edca_process_fu_240_be_backoff_counter_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_CW_be_o;
wire    grp_initial_edca_process_fu_240_CW_be_o_ap_vld;
wire   [2:0] grp_initial_edca_process_fu_240_available_spaces_bk_o;
wire    grp_initial_edca_process_fu_240_available_spaces_bk_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_bk_backoff_counter_o;
wire    grp_initial_edca_process_fu_240_bk_backoff_counter_o_ap_vld;
wire   [9:0] grp_initial_edca_process_fu_240_CW_bk_o;
wire    grp_initial_edca_process_fu_240_CW_bk_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_write_pointer_bk_o;
wire    grp_initial_edca_process_fu_240_write_pointer_bk_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_write_pointer_be_o;
wire    grp_initial_edca_process_fu_240_write_pointer_be_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_write_pointer_vi_o;
wire    grp_initial_edca_process_fu_240_write_pointer_vi_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_write_pointer_vo_o;
wire    grp_initial_edca_process_fu_240_write_pointer_vo_o_ap_vld;
wire   [10:0] grp_initial_edca_process_fu_240_edca_queues_address0;
wire    grp_initial_edca_process_fu_240_edca_queues_ce0;
wire    grp_initial_edca_process_fu_240_edca_queues_we0;
wire   [7:0] grp_initial_edca_process_fu_240_edca_queues_d0;
wire   [1:0] grp_initial_edca_process_fu_240_read_pointer_bk_o;
wire    grp_initial_edca_process_fu_240_read_pointer_bk_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_read_pointer_be_o;
wire    grp_initial_edca_process_fu_240_read_pointer_be_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_read_pointer_vi_o;
wire    grp_initial_edca_process_fu_240_read_pointer_vi_o_ap_vld;
wire   [1:0] grp_initial_edca_process_fu_240_read_pointer_vo_o;
wire    grp_initial_edca_process_fu_240_read_pointer_vo_o_ap_vld;
wire    grp_phy_txend_confirm_fu_292_ap_start;
wire    grp_phy_txend_confirm_fu_292_ap_done;
wire    grp_phy_txend_confirm_fu_292_ap_idle;
wire    grp_phy_txend_confirm_fu_292_ap_ready;
wire   [2:0] grp_phy_txend_confirm_fu_292_current_txop_holder_o;
wire    grp_phy_txend_confirm_fu_292_current_txop_holder_o_ap_vld;
wire   [6:0] grp_phy_txend_confirm_fu_292_frame_to_transfer_address0;
wire    grp_phy_txend_confirm_fu_292_frame_to_transfer_ce0;
wire    grp_phy_txend_confirm_fu_292_frame_to_transfer_we0;
wire   [7:0] grp_phy_txend_confirm_fu_292_frame_to_transfer_d0;
wire   [2:0] grp_phy_txend_confirm_fu_292_available_spaces_vo_o;
wire    grp_phy_txend_confirm_fu_292_available_spaces_vo_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_vo_backoff_counter_o;
wire    grp_phy_txend_confirm_fu_292_vo_backoff_counter_o_ap_vld;
wire   [31:0] grp_phy_txend_confirm_fu_292_rand_state_o;
wire    grp_phy_txend_confirm_fu_292_rand_state_o_ap_vld;
wire   [2:0] grp_phy_txend_confirm_fu_292_available_spaces_vi_o;
wire    grp_phy_txend_confirm_fu_292_available_spaces_vi_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_vi_backoff_counter_o;
wire    grp_phy_txend_confirm_fu_292_vi_backoff_counter_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_CW_vi_o;
wire    grp_phy_txend_confirm_fu_292_CW_vi_o_ap_vld;
wire   [2:0] grp_phy_txend_confirm_fu_292_available_spaces_be_o;
wire    grp_phy_txend_confirm_fu_292_available_spaces_be_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_be_backoff_counter_o;
wire    grp_phy_txend_confirm_fu_292_be_backoff_counter_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_CW_be_o;
wire    grp_phy_txend_confirm_fu_292_CW_be_o_ap_vld;
wire   [2:0] grp_phy_txend_confirm_fu_292_available_spaces_bk_o;
wire    grp_phy_txend_confirm_fu_292_available_spaces_bk_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_bk_backoff_counter_o;
wire    grp_phy_txend_confirm_fu_292_bk_backoff_counter_o_ap_vld;
wire   [9:0] grp_phy_txend_confirm_fu_292_CW_bk_o;
wire    grp_phy_txend_confirm_fu_292_CW_bk_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_write_pointer_bk_o;
wire    grp_phy_txend_confirm_fu_292_write_pointer_bk_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_write_pointer_be_o;
wire    grp_phy_txend_confirm_fu_292_write_pointer_be_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_write_pointer_vi_o;
wire    grp_phy_txend_confirm_fu_292_write_pointer_vi_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_write_pointer_vo_o;
wire    grp_phy_txend_confirm_fu_292_write_pointer_vo_o_ap_vld;
wire   [10:0] grp_phy_txend_confirm_fu_292_edca_queues_address0;
wire    grp_phy_txend_confirm_fu_292_edca_queues_ce0;
wire    grp_phy_txend_confirm_fu_292_edca_queues_we0;
wire   [7:0] grp_phy_txend_confirm_fu_292_edca_queues_d0;
wire   [1:0] grp_phy_txend_confirm_fu_292_read_pointer_bk_o;
wire    grp_phy_txend_confirm_fu_292_read_pointer_bk_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_read_pointer_be_o;
wire    grp_phy_txend_confirm_fu_292_read_pointer_be_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_read_pointer_vi_o;
wire    grp_phy_txend_confirm_fu_292_read_pointer_vi_o_ap_vld;
wire   [1:0] grp_phy_txend_confirm_fu_292_read_pointer_vo_o;
wire    grp_phy_txend_confirm_fu_292_read_pointer_vo_o_ap_vld;
wire    grp_ma_unitdatax_request_fu_344_ap_start;
wire    grp_ma_unitdatax_request_fu_344_ap_done;
wire    grp_ma_unitdatax_request_fu_344_ap_idle;
wire    grp_ma_unitdatax_request_fu_344_ap_ready;
wire   [2:0] grp_ma_unitdatax_request_fu_344_source_addr_mac_address0;
wire    grp_ma_unitdatax_request_fu_344_source_addr_mac_ce0;
wire   [2:0] grp_ma_unitdatax_request_fu_344_source_addr_mac_address1;
wire    grp_ma_unitdatax_request_fu_344_source_addr_mac_ce1;
wire   [6:0] grp_ma_unitdatax_request_fu_344_data_address0;
wire    grp_ma_unitdatax_request_fu_344_data_ce0;
wire   [2:0] grp_ma_unitdatax_request_fu_344_available_spaces_bk_o;
wire    grp_ma_unitdatax_request_fu_344_available_spaces_bk_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_write_pointer_bk_o;
wire    grp_ma_unitdatax_request_fu_344_write_pointer_bk_o_ap_vld;
wire   [2:0] grp_ma_unitdatax_request_fu_344_available_spaces_be_o;
wire    grp_ma_unitdatax_request_fu_344_available_spaces_be_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_write_pointer_be_o;
wire    grp_ma_unitdatax_request_fu_344_write_pointer_be_o_ap_vld;
wire   [2:0] grp_ma_unitdatax_request_fu_344_available_spaces_vi_o;
wire    grp_ma_unitdatax_request_fu_344_available_spaces_vi_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_write_pointer_vi_o;
wire    grp_ma_unitdatax_request_fu_344_write_pointer_vi_o_ap_vld;
wire   [2:0] grp_ma_unitdatax_request_fu_344_available_spaces_vo_o;
wire    grp_ma_unitdatax_request_fu_344_available_spaces_vo_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_write_pointer_vo_o;
wire    grp_ma_unitdatax_request_fu_344_write_pointer_vo_o_ap_vld;
wire   [10:0] grp_ma_unitdatax_request_fu_344_edca_queues_address0;
wire    grp_ma_unitdatax_request_fu_344_edca_queues_ce0;
wire    grp_ma_unitdatax_request_fu_344_edca_queues_we0;
wire   [7:0] grp_ma_unitdatax_request_fu_344_edca_queues_d0;
wire   [1:0] grp_ma_unitdatax_request_fu_344_read_pointer_bk_o;
wire    grp_ma_unitdatax_request_fu_344_read_pointer_bk_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_read_pointer_be_o;
wire    grp_ma_unitdatax_request_fu_344_read_pointer_be_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_read_pointer_vi_o;
wire    grp_ma_unitdatax_request_fu_344_read_pointer_vi_o_ap_vld;
wire   [1:0] grp_ma_unitdatax_request_fu_344_read_pointer_vo_o;
wire    grp_ma_unitdatax_request_fu_344_read_pointer_vo_o_ap_vld;
wire   [31:0] grp_ma_unitdatax_request_fu_344_rand_state_o;
wire    grp_ma_unitdatax_request_fu_344_rand_state_o_ap_vld;
wire   [9:0] grp_ma_unitdatax_request_fu_344_bk_backoff_counter;
wire    grp_ma_unitdatax_request_fu_344_bk_backoff_counter_ap_vld;
wire   [9:0] grp_ma_unitdatax_request_fu_344_be_backoff_counter;
wire    grp_ma_unitdatax_request_fu_344_be_backoff_counter_ap_vld;
wire   [9:0] grp_ma_unitdatax_request_fu_344_vi_backoff_counter;
wire    grp_ma_unitdatax_request_fu_344_vi_backoff_counter_ap_vld;
wire   [9:0] grp_ma_unitdatax_request_fu_344_vo_backoff_counter;
wire    grp_ma_unitdatax_request_fu_344_vo_backoff_counter_ap_vld;
wire    grp_phy_data_request_fu_422_ap_start;
wire    grp_phy_data_request_fu_422_ap_done;
wire    grp_phy_data_request_fu_422_ap_idle;
wire    grp_phy_data_request_fu_422_ap_ready;
wire   [6:0] grp_phy_data_request_fu_422_data_address0;
wire    grp_phy_data_request_fu_422_data_ce0;
reg    call_ln17_phy_txend_request_fu_429_ap_start;
wire    call_ln17_phy_txend_request_fu_429_ap_done;
wire    call_ln17_phy_txend_request_fu_429_ap_idle;
wire    call_ln17_phy_txend_request_fu_429_ap_ready;
wire    call_ln6_phy_data_request_1_fu_435_ap_ready;
reg   [6:0] i_0_reg_208;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state13;
reg    ap_block_state13_on_subcall_done;
reg   [6:0] q_0_i_reg_219;
wire    ap_CS_fsm_state12;
reg   [6:0] ap_phi_mux_count_new_0_i_phi_fu_233_p4;
reg    grp_initial_edca_process_fu_240_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_phy_txend_confirm_fu_292_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_ma_unitdatax_request_fu_344_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
reg    grp_phy_data_request_fu_422_ap_start_reg;
reg   [7:0] data_1_fu_132;
wire    ap_CS_fsm_state8;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 available_spaces_bk = 3'd4;
#0 write_pointer_bk = 2'd0;
#0 available_spaces_be = 3'd4;
#0 write_pointer_be = 2'd0;
#0 available_spaces_vi = 3'd4;
#0 write_pointer_vi = 2'd0;
#0 available_spaces_vo = 3'd4;
#0 write_pointer_vo = 2'd0;
#0 read_pointer_bk = 2'd0;
#0 read_pointer_be = 2'd0;
#0 read_pointer_vi = 2'd0;
#0 read_pointer_vo = 2'd0;
#0 CW_bk = 10'd15;
#0 rand_state = 32'd123456789;
#0 bk_backoff_counter = 10'd0;
#0 CW_be = 10'd15;
#0 be_backoff_counter = 10'd0;
#0 CW_vi = 10'd15;
#0 vi_backoff_counter = 10'd0;
#0 vo_backoff_counter = 10'd0;
#0 count = 7'd0;
#0 grp_initial_edca_process_fu_240_ap_start_reg = 1'b0;
#0 grp_phy_txend_confirm_fu_292_ap_start_reg = 1'b0;
#0 grp_ma_unitdatax_request_fu_344_ap_start_reg = 1'b0;
#0 grp_phy_data_request_fu_422_ap_start_reg = 1'b0;
end

send_frame_edca_qfYi #(
    .DataWidth( 8 ),
    .AddressRange( 1600 ),
    .AddressWidth( 11 ))
edca_queues_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(edca_queues_address0),
    .ce0(edca_queues_ce0),
    .we0(edca_queues_we0),
    .d0(edca_queues_d0),
    .q0(edca_queues_q0)
);

send_frame_frame #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
frame_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(frame_address0),
    .ce0(frame_ce0),
    .we0(frame_we0),
    .d0(mac_frame_q0),
    .q0(frame_q0)
);

initial_edca_process grp_initial_edca_process_fu_240(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_initial_edca_process_fu_240_ap_start),
    .ap_done(grp_initial_edca_process_fu_240_ap_done),
    .ap_idle(grp_initial_edca_process_fu_240_ap_idle),
    .ap_ready(grp_initial_edca_process_fu_240_ap_ready),
    .medium_state(medium_state),
    .current_txop_holder_i(current_txop_holder_i),
    .current_txop_holder_o(grp_initial_edca_process_fu_240_current_txop_holder_o),
    .current_txop_holder_o_ap_vld(grp_initial_edca_process_fu_240_current_txop_holder_o_ap_vld),
    .frame_to_transfer_address0(grp_initial_edca_process_fu_240_frame_to_transfer_address0),
    .frame_to_transfer_ce0(grp_initial_edca_process_fu_240_frame_to_transfer_ce0),
    .frame_to_transfer_we0(grp_initial_edca_process_fu_240_frame_to_transfer_we0),
    .frame_to_transfer_d0(grp_initial_edca_process_fu_240_frame_to_transfer_d0),
    .frame_to_transfer_q0(mac_frame_q0),
    .available_spaces_vo_i(available_spaces_vo),
    .available_spaces_vo_o(grp_initial_edca_process_fu_240_available_spaces_vo_o),
    .available_spaces_vo_o_ap_vld(grp_initial_edca_process_fu_240_available_spaces_vo_o_ap_vld),
    .vo_backoff_counter_i(vo_backoff_counter),
    .vo_backoff_counter_o(grp_initial_edca_process_fu_240_vo_backoff_counter_o),
    .vo_backoff_counter_o_ap_vld(grp_initial_edca_process_fu_240_vo_backoff_counter_o_ap_vld),
    .rand_state_i(rand_state),
    .rand_state_o(grp_initial_edca_process_fu_240_rand_state_o),
    .rand_state_o_ap_vld(grp_initial_edca_process_fu_240_rand_state_o_ap_vld),
    .available_spaces_vi_i(available_spaces_vi),
    .available_spaces_vi_o(grp_initial_edca_process_fu_240_available_spaces_vi_o),
    .available_spaces_vi_o_ap_vld(grp_initial_edca_process_fu_240_available_spaces_vi_o_ap_vld),
    .vi_backoff_counter_i(vi_backoff_counter),
    .vi_backoff_counter_o(grp_initial_edca_process_fu_240_vi_backoff_counter_o),
    .vi_backoff_counter_o_ap_vld(grp_initial_edca_process_fu_240_vi_backoff_counter_o_ap_vld),
    .CW_vi_i(CW_vi),
    .CW_vi_o(grp_initial_edca_process_fu_240_CW_vi_o),
    .CW_vi_o_ap_vld(grp_initial_edca_process_fu_240_CW_vi_o_ap_vld),
    .available_spaces_be_i(available_spaces_be),
    .available_spaces_be_o(grp_initial_edca_process_fu_240_available_spaces_be_o),
    .available_spaces_be_o_ap_vld(grp_initial_edca_process_fu_240_available_spaces_be_o_ap_vld),
    .be_backoff_counter_i(be_backoff_counter),
    .be_backoff_counter_o(grp_initial_edca_process_fu_240_be_backoff_counter_o),
    .be_backoff_counter_o_ap_vld(grp_initial_edca_process_fu_240_be_backoff_counter_o_ap_vld),
    .CW_be_i(CW_be),
    .CW_be_o(grp_initial_edca_process_fu_240_CW_be_o),
    .CW_be_o_ap_vld(grp_initial_edca_process_fu_240_CW_be_o_ap_vld),
    .available_spaces_bk_i(available_spaces_bk),
    .available_spaces_bk_o(grp_initial_edca_process_fu_240_available_spaces_bk_o),
    .available_spaces_bk_o_ap_vld(grp_initial_edca_process_fu_240_available_spaces_bk_o_ap_vld),
    .bk_backoff_counter_i(bk_backoff_counter),
    .bk_backoff_counter_o(grp_initial_edca_process_fu_240_bk_backoff_counter_o),
    .bk_backoff_counter_o_ap_vld(grp_initial_edca_process_fu_240_bk_backoff_counter_o_ap_vld),
    .CW_bk_i(CW_bk),
    .CW_bk_o(grp_initial_edca_process_fu_240_CW_bk_o),
    .CW_bk_o_ap_vld(grp_initial_edca_process_fu_240_CW_bk_o_ap_vld),
    .write_pointer_bk_i(write_pointer_bk),
    .write_pointer_bk_o(grp_initial_edca_process_fu_240_write_pointer_bk_o),
    .write_pointer_bk_o_ap_vld(grp_initial_edca_process_fu_240_write_pointer_bk_o_ap_vld),
    .write_pointer_be_i(write_pointer_be),
    .write_pointer_be_o(grp_initial_edca_process_fu_240_write_pointer_be_o),
    .write_pointer_be_o_ap_vld(grp_initial_edca_process_fu_240_write_pointer_be_o_ap_vld),
    .write_pointer_vi_i(write_pointer_vi),
    .write_pointer_vi_o(grp_initial_edca_process_fu_240_write_pointer_vi_o),
    .write_pointer_vi_o_ap_vld(grp_initial_edca_process_fu_240_write_pointer_vi_o_ap_vld),
    .write_pointer_vo_i(write_pointer_vo),
    .write_pointer_vo_o(grp_initial_edca_process_fu_240_write_pointer_vo_o),
    .write_pointer_vo_o_ap_vld(grp_initial_edca_process_fu_240_write_pointer_vo_o_ap_vld),
    .edca_queues_address0(grp_initial_edca_process_fu_240_edca_queues_address0),
    .edca_queues_ce0(grp_initial_edca_process_fu_240_edca_queues_ce0),
    .edca_queues_we0(grp_initial_edca_process_fu_240_edca_queues_we0),
    .edca_queues_d0(grp_initial_edca_process_fu_240_edca_queues_d0),
    .edca_queues_q0(edca_queues_q0),
    .read_pointer_bk_i(read_pointer_bk),
    .read_pointer_bk_o(grp_initial_edca_process_fu_240_read_pointer_bk_o),
    .read_pointer_bk_o_ap_vld(grp_initial_edca_process_fu_240_read_pointer_bk_o_ap_vld),
    .read_pointer_be_i(read_pointer_be),
    .read_pointer_be_o(grp_initial_edca_process_fu_240_read_pointer_be_o),
    .read_pointer_be_o_ap_vld(grp_initial_edca_process_fu_240_read_pointer_be_o_ap_vld),
    .read_pointer_vi_i(read_pointer_vi),
    .read_pointer_vi_o(grp_initial_edca_process_fu_240_read_pointer_vi_o),
    .read_pointer_vi_o_ap_vld(grp_initial_edca_process_fu_240_read_pointer_vi_o_ap_vld),
    .read_pointer_vo_i(read_pointer_vo),
    .read_pointer_vo_o(grp_initial_edca_process_fu_240_read_pointer_vo_o),
    .read_pointer_vo_o_ap_vld(grp_initial_edca_process_fu_240_read_pointer_vo_o_ap_vld)
);

phy_txend_confirm grp_phy_txend_confirm_fu_292(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_phy_txend_confirm_fu_292_ap_start),
    .ap_done(grp_phy_txend_confirm_fu_292_ap_done),
    .ap_idle(grp_phy_txend_confirm_fu_292_ap_idle),
    .ap_ready(grp_phy_txend_confirm_fu_292_ap_ready),
    .medium_state(medium_state),
    .current_txop_holder_i(current_txop_holder_i),
    .current_txop_holder_o(grp_phy_txend_confirm_fu_292_current_txop_holder_o),
    .current_txop_holder_o_ap_vld(grp_phy_txend_confirm_fu_292_current_txop_holder_o_ap_vld),
    .frame_to_transfer_address0(grp_phy_txend_confirm_fu_292_frame_to_transfer_address0),
    .frame_to_transfer_ce0(grp_phy_txend_confirm_fu_292_frame_to_transfer_ce0),
    .frame_to_transfer_we0(grp_phy_txend_confirm_fu_292_frame_to_transfer_we0),
    .frame_to_transfer_d0(grp_phy_txend_confirm_fu_292_frame_to_transfer_d0),
    .frame_to_transfer_q0(mac_frame_q0),
    .available_spaces_vo_i(available_spaces_vo),
    .available_spaces_vo_o(grp_phy_txend_confirm_fu_292_available_spaces_vo_o),
    .available_spaces_vo_o_ap_vld(grp_phy_txend_confirm_fu_292_available_spaces_vo_o_ap_vld),
    .vo_backoff_counter_i(vo_backoff_counter),
    .vo_backoff_counter_o(grp_phy_txend_confirm_fu_292_vo_backoff_counter_o),
    .vo_backoff_counter_o_ap_vld(grp_phy_txend_confirm_fu_292_vo_backoff_counter_o_ap_vld),
    .rand_state_i(rand_state),
    .rand_state_o(grp_phy_txend_confirm_fu_292_rand_state_o),
    .rand_state_o_ap_vld(grp_phy_txend_confirm_fu_292_rand_state_o_ap_vld),
    .available_spaces_vi_i(available_spaces_vi),
    .available_spaces_vi_o(grp_phy_txend_confirm_fu_292_available_spaces_vi_o),
    .available_spaces_vi_o_ap_vld(grp_phy_txend_confirm_fu_292_available_spaces_vi_o_ap_vld),
    .vi_backoff_counter_i(vi_backoff_counter),
    .vi_backoff_counter_o(grp_phy_txend_confirm_fu_292_vi_backoff_counter_o),
    .vi_backoff_counter_o_ap_vld(grp_phy_txend_confirm_fu_292_vi_backoff_counter_o_ap_vld),
    .CW_vi_i(CW_vi),
    .CW_vi_o(grp_phy_txend_confirm_fu_292_CW_vi_o),
    .CW_vi_o_ap_vld(grp_phy_txend_confirm_fu_292_CW_vi_o_ap_vld),
    .available_spaces_be_i(available_spaces_be),
    .available_spaces_be_o(grp_phy_txend_confirm_fu_292_available_spaces_be_o),
    .available_spaces_be_o_ap_vld(grp_phy_txend_confirm_fu_292_available_spaces_be_o_ap_vld),
    .be_backoff_counter_i(be_backoff_counter),
    .be_backoff_counter_o(grp_phy_txend_confirm_fu_292_be_backoff_counter_o),
    .be_backoff_counter_o_ap_vld(grp_phy_txend_confirm_fu_292_be_backoff_counter_o_ap_vld),
    .CW_be_i(CW_be),
    .CW_be_o(grp_phy_txend_confirm_fu_292_CW_be_o),
    .CW_be_o_ap_vld(grp_phy_txend_confirm_fu_292_CW_be_o_ap_vld),
    .available_spaces_bk_i(available_spaces_bk),
    .available_spaces_bk_o(grp_phy_txend_confirm_fu_292_available_spaces_bk_o),
    .available_spaces_bk_o_ap_vld(grp_phy_txend_confirm_fu_292_available_spaces_bk_o_ap_vld),
    .bk_backoff_counter_i(bk_backoff_counter),
    .bk_backoff_counter_o(grp_phy_txend_confirm_fu_292_bk_backoff_counter_o),
    .bk_backoff_counter_o_ap_vld(grp_phy_txend_confirm_fu_292_bk_backoff_counter_o_ap_vld),
    .CW_bk_i(CW_bk),
    .CW_bk_o(grp_phy_txend_confirm_fu_292_CW_bk_o),
    .CW_bk_o_ap_vld(grp_phy_txend_confirm_fu_292_CW_bk_o_ap_vld),
    .write_pointer_bk_i(write_pointer_bk),
    .write_pointer_bk_o(grp_phy_txend_confirm_fu_292_write_pointer_bk_o),
    .write_pointer_bk_o_ap_vld(grp_phy_txend_confirm_fu_292_write_pointer_bk_o_ap_vld),
    .write_pointer_be_i(write_pointer_be),
    .write_pointer_be_o(grp_phy_txend_confirm_fu_292_write_pointer_be_o),
    .write_pointer_be_o_ap_vld(grp_phy_txend_confirm_fu_292_write_pointer_be_o_ap_vld),
    .write_pointer_vi_i(write_pointer_vi),
    .write_pointer_vi_o(grp_phy_txend_confirm_fu_292_write_pointer_vi_o),
    .write_pointer_vi_o_ap_vld(grp_phy_txend_confirm_fu_292_write_pointer_vi_o_ap_vld),
    .write_pointer_vo_i(write_pointer_vo),
    .write_pointer_vo_o(grp_phy_txend_confirm_fu_292_write_pointer_vo_o),
    .write_pointer_vo_o_ap_vld(grp_phy_txend_confirm_fu_292_write_pointer_vo_o_ap_vld),
    .edca_queues_address0(grp_phy_txend_confirm_fu_292_edca_queues_address0),
    .edca_queues_ce0(grp_phy_txend_confirm_fu_292_edca_queues_ce0),
    .edca_queues_we0(grp_phy_txend_confirm_fu_292_edca_queues_we0),
    .edca_queues_d0(grp_phy_txend_confirm_fu_292_edca_queues_d0),
    .edca_queues_q0(edca_queues_q0),
    .read_pointer_bk_i(read_pointer_bk),
    .read_pointer_bk_o(grp_phy_txend_confirm_fu_292_read_pointer_bk_o),
    .read_pointer_bk_o_ap_vld(grp_phy_txend_confirm_fu_292_read_pointer_bk_o_ap_vld),
    .read_pointer_be_i(read_pointer_be),
    .read_pointer_be_o(grp_phy_txend_confirm_fu_292_read_pointer_be_o),
    .read_pointer_be_o_ap_vld(grp_phy_txend_confirm_fu_292_read_pointer_be_o_ap_vld),
    .read_pointer_vi_i(read_pointer_vi),
    .read_pointer_vi_o(grp_phy_txend_confirm_fu_292_read_pointer_vi_o),
    .read_pointer_vi_o_ap_vld(grp_phy_txend_confirm_fu_292_read_pointer_vi_o_ap_vld),
    .read_pointer_vo_i(read_pointer_vo),
    .read_pointer_vo_o(grp_phy_txend_confirm_fu_292_read_pointer_vo_o),
    .read_pointer_vo_o_ap_vld(grp_phy_txend_confirm_fu_292_read_pointer_vo_o_ap_vld)
);

ma_unitdatax_request grp_ma_unitdatax_request_fu_344(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ma_unitdatax_request_fu_344_ap_start),
    .ap_done(grp_ma_unitdatax_request_fu_344_ap_done),
    .ap_idle(grp_ma_unitdatax_request_fu_344_ap_idle),
    .ap_ready(grp_ma_unitdatax_request_fu_344_ap_ready),
    .source_addr_mac_address0(grp_ma_unitdatax_request_fu_344_source_addr_mac_address0),
    .source_addr_mac_ce0(grp_ma_unitdatax_request_fu_344_source_addr_mac_ce0),
    .source_addr_mac_q0(source_addr_mac_q0),
    .source_addr_mac_address1(grp_ma_unitdatax_request_fu_344_source_addr_mac_address1),
    .source_addr_mac_ce1(grp_ma_unitdatax_request_fu_344_source_addr_mac_ce1),
    .source_addr_mac_q1(source_addr_mac_q1),
    .data_address0(grp_ma_unitdatax_request_fu_344_data_address0),
    .data_ce0(grp_ma_unitdatax_request_fu_344_data_ce0),
    .data_q0(data_q0),
    .up(up),
    .s_class(s_class),
    .c_identifier_operating_class(c_identifier_operating_class),
    .c_identifier_channel_number(c_identifier_channel_number),
    .d_rate(d_rate),
    .tx_power_lvl(tx_power_lvl),
    .medium_state(medium_state),
    .available_spaces_bk_i(available_spaces_bk),
    .available_spaces_bk_o(grp_ma_unitdatax_request_fu_344_available_spaces_bk_o),
    .available_spaces_bk_o_ap_vld(grp_ma_unitdatax_request_fu_344_available_spaces_bk_o_ap_vld),
    .write_pointer_bk_i(write_pointer_bk),
    .write_pointer_bk_o(grp_ma_unitdatax_request_fu_344_write_pointer_bk_o),
    .write_pointer_bk_o_ap_vld(grp_ma_unitdatax_request_fu_344_write_pointer_bk_o_ap_vld),
    .available_spaces_be_i(available_spaces_be),
    .available_spaces_be_o(grp_ma_unitdatax_request_fu_344_available_spaces_be_o),
    .available_spaces_be_o_ap_vld(grp_ma_unitdatax_request_fu_344_available_spaces_be_o_ap_vld),
    .write_pointer_be_i(write_pointer_be),
    .write_pointer_be_o(grp_ma_unitdatax_request_fu_344_write_pointer_be_o),
    .write_pointer_be_o_ap_vld(grp_ma_unitdatax_request_fu_344_write_pointer_be_o_ap_vld),
    .available_spaces_vi_i(available_spaces_vi),
    .available_spaces_vi_o(grp_ma_unitdatax_request_fu_344_available_spaces_vi_o),
    .available_spaces_vi_o_ap_vld(grp_ma_unitdatax_request_fu_344_available_spaces_vi_o_ap_vld),
    .write_pointer_vi_i(write_pointer_vi),
    .write_pointer_vi_o(grp_ma_unitdatax_request_fu_344_write_pointer_vi_o),
    .write_pointer_vi_o_ap_vld(grp_ma_unitdatax_request_fu_344_write_pointer_vi_o_ap_vld),
    .available_spaces_vo_i(available_spaces_vo),
    .available_spaces_vo_o(grp_ma_unitdatax_request_fu_344_available_spaces_vo_o),
    .available_spaces_vo_o_ap_vld(grp_ma_unitdatax_request_fu_344_available_spaces_vo_o_ap_vld),
    .write_pointer_vo_i(write_pointer_vo),
    .write_pointer_vo_o(grp_ma_unitdatax_request_fu_344_write_pointer_vo_o),
    .write_pointer_vo_o_ap_vld(grp_ma_unitdatax_request_fu_344_write_pointer_vo_o_ap_vld),
    .edca_queues_address0(grp_ma_unitdatax_request_fu_344_edca_queues_address0),
    .edca_queues_ce0(grp_ma_unitdatax_request_fu_344_edca_queues_ce0),
    .edca_queues_we0(grp_ma_unitdatax_request_fu_344_edca_queues_we0),
    .edca_queues_d0(grp_ma_unitdatax_request_fu_344_edca_queues_d0),
    .edca_queues_q0(edca_queues_q0),
    .read_pointer_bk_i(read_pointer_bk),
    .read_pointer_bk_o(grp_ma_unitdatax_request_fu_344_read_pointer_bk_o),
    .read_pointer_bk_o_ap_vld(grp_ma_unitdatax_request_fu_344_read_pointer_bk_o_ap_vld),
    .read_pointer_be_i(read_pointer_be),
    .read_pointer_be_o(grp_ma_unitdatax_request_fu_344_read_pointer_be_o),
    .read_pointer_be_o_ap_vld(grp_ma_unitdatax_request_fu_344_read_pointer_be_o_ap_vld),
    .read_pointer_vi_i(read_pointer_vi),
    .read_pointer_vi_o(grp_ma_unitdatax_request_fu_344_read_pointer_vi_o),
    .read_pointer_vi_o_ap_vld(grp_ma_unitdatax_request_fu_344_read_pointer_vi_o_ap_vld),
    .read_pointer_vo_i(read_pointer_vo),
    .read_pointer_vo_o(grp_ma_unitdatax_request_fu_344_read_pointer_vo_o),
    .read_pointer_vo_o_ap_vld(grp_ma_unitdatax_request_fu_344_read_pointer_vo_o_ap_vld),
    .CW_bk(CW_bk),
    .rand_state_i(rand_state),
    .rand_state_o(grp_ma_unitdatax_request_fu_344_rand_state_o),
    .rand_state_o_ap_vld(grp_ma_unitdatax_request_fu_344_rand_state_o_ap_vld),
    .bk_backoff_counter(grp_ma_unitdatax_request_fu_344_bk_backoff_counter),
    .bk_backoff_counter_ap_vld(grp_ma_unitdatax_request_fu_344_bk_backoff_counter_ap_vld),
    .CW_be(CW_be),
    .be_backoff_counter(grp_ma_unitdatax_request_fu_344_be_backoff_counter),
    .be_backoff_counter_ap_vld(grp_ma_unitdatax_request_fu_344_be_backoff_counter_ap_vld),
    .CW_vi(CW_vi),
    .vi_backoff_counter(grp_ma_unitdatax_request_fu_344_vi_backoff_counter),
    .vi_backoff_counter_ap_vld(grp_ma_unitdatax_request_fu_344_vi_backoff_counter_ap_vld),
    .vo_backoff_counter(grp_ma_unitdatax_request_fu_344_vo_backoff_counter),
    .vo_backoff_counter_ap_vld(grp_ma_unitdatax_request_fu_344_vo_backoff_counter_ap_vld)
);

phy_data_request grp_phy_data_request_fu_422(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_phy_data_request_fu_422_ap_start),
    .ap_done(grp_phy_data_request_fu_422_ap_done),
    .ap_idle(grp_phy_data_request_fu_422_ap_idle),
    .ap_ready(grp_phy_data_request_fu_422_ap_ready),
    .data_address0(grp_phy_data_request_fu_422_data_address0),
    .data_ce0(grp_phy_data_request_fu_422_data_ce0),
    .data_q0(frame_q0),
    .data_offset(add_ln15_reg_578)
);

phy_txend_request call_ln17_phy_txend_request_fu_429(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln17_phy_txend_request_fu_429_ap_start),
    .ap_done(call_ln17_phy_txend_request_fu_429_ap_done),
    .ap_idle(call_ln17_phy_txend_request_fu_429_ap_idle),
    .ap_ready(call_ln17_phy_txend_request_fu_429_ap_ready)
);

phy_data_request_1 call_ln6_phy_data_request_1_fu_435(
    .ap_ready(call_ln6_phy_data_request_1_fu_435_ap_ready),
    .data(data_1_fu_132)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_initial_edca_process_fu_240_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_initial_edca_process_fu_240_ap_start_reg <= 1'b1;
        end else if ((grp_initial_edca_process_fu_240_ap_ready == 1'b1)) begin
            grp_initial_edca_process_fu_240_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ma_unitdatax_request_fu_344_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
            grp_ma_unitdatax_request_fu_344_ap_start_reg <= 1'b1;
        end else if ((grp_ma_unitdatax_request_fu_344_ap_ready == 1'b1)) begin
            grp_ma_unitdatax_request_fu_344_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_phy_data_request_fu_422_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) & (((icmp_ln16_fu_490_p2 == 1'd0) & (icmp_ln10_reg_556 == 1'd0)) | ((icmp_ln11_fu_467_p2 == 1'd1) & (icmp_ln16_fu_490_p2 == 1'd0))))) begin
            grp_phy_data_request_fu_422_ap_start_reg <= 1'b1;
        end else if ((grp_phy_data_request_fu_422_ap_ready == 1'b1)) begin
            grp_phy_data_request_fu_422_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_phy_txend_confirm_fu_292_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln22_fu_445_p2 == 1'd1))) begin
            grp_phy_txend_confirm_fu_292_ap_start_reg <= 1'b1;
        end else if ((grp_phy_txend_confirm_fu_292_ap_ready == 1'b1)) begin
            grp_phy_txend_confirm_fu_292_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_CW_be_o_ap_vld == 1'b1))) begin
        CW_be <= grp_phy_txend_confirm_fu_292_CW_be_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_CW_be_o_ap_vld == 1'b1))) begin
        CW_be <= grp_initial_edca_process_fu_240_CW_be_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_CW_bk_o_ap_vld == 1'b1))) begin
        CW_bk <= grp_phy_txend_confirm_fu_292_CW_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_CW_bk_o_ap_vld == 1'b1))) begin
        CW_bk <= grp_initial_edca_process_fu_240_CW_bk_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_CW_vi_o_ap_vld == 1'b1))) begin
        CW_vi <= grp_phy_txend_confirm_fu_292_CW_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_CW_vi_o_ap_vld == 1'b1))) begin
        CW_vi <= grp_initial_edca_process_fu_240_CW_vi_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_available_spaces_be_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_available_spaces_be_o_ap_vld == 1'b1)))) begin
        available_spaces_be <= grp_ma_unitdatax_request_fu_344_available_spaces_be_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_available_spaces_be_o_ap_vld == 1'b1))) begin
        available_spaces_be <= grp_phy_txend_confirm_fu_292_available_spaces_be_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_available_spaces_be_o_ap_vld == 1'b1))) begin
        available_spaces_be <= grp_initial_edca_process_fu_240_available_spaces_be_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_available_spaces_bk_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_available_spaces_bk_o_ap_vld == 1'b1)))) begin
        available_spaces_bk <= grp_ma_unitdatax_request_fu_344_available_spaces_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_available_spaces_bk_o_ap_vld == 1'b1))) begin
        available_spaces_bk <= grp_phy_txend_confirm_fu_292_available_spaces_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_available_spaces_bk_o_ap_vld == 1'b1))) begin
        available_spaces_bk <= grp_initial_edca_process_fu_240_available_spaces_bk_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_available_spaces_vi_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_available_spaces_vi_o_ap_vld == 1'b1)))) begin
        available_spaces_vi <= grp_ma_unitdatax_request_fu_344_available_spaces_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_available_spaces_vi_o_ap_vld == 1'b1))) begin
        available_spaces_vi <= grp_phy_txend_confirm_fu_292_available_spaces_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_available_spaces_vi_o_ap_vld == 1'b1))) begin
        available_spaces_vi <= grp_initial_edca_process_fu_240_available_spaces_vi_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_available_spaces_vo_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_available_spaces_vo_o_ap_vld == 1'b1)))) begin
        available_spaces_vo <= grp_ma_unitdatax_request_fu_344_available_spaces_vo_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_available_spaces_vo_o_ap_vld == 1'b1))) begin
        available_spaces_vo <= grp_phy_txend_confirm_fu_292_available_spaces_vo_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_available_spaces_vo_o_ap_vld == 1'b1))) begin
        available_spaces_vo <= grp_initial_edca_process_fu_240_available_spaces_vo_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_be_backoff_counter_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_be_backoff_counter_ap_vld == 1'b1)))) begin
        be_backoff_counter <= grp_ma_unitdatax_request_fu_344_be_backoff_counter;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_be_backoff_counter_o_ap_vld == 1'b1))) begin
        be_backoff_counter <= grp_phy_txend_confirm_fu_292_be_backoff_counter_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_be_backoff_counter_o_ap_vld == 1'b1))) begin
        be_backoff_counter <= grp_initial_edca_process_fu_240_be_backoff_counter_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_bk_backoff_counter_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_bk_backoff_counter_ap_vld == 1'b1)))) begin
        bk_backoff_counter <= grp_ma_unitdatax_request_fu_344_bk_backoff_counter;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_bk_backoff_counter_o_ap_vld == 1'b1))) begin
        bk_backoff_counter <= grp_phy_txend_confirm_fu_292_bk_backoff_counter_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_bk_backoff_counter_o_ap_vld == 1'b1))) begin
        bk_backoff_counter <= grp_initial_edca_process_fu_240_bk_backoff_counter_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13))) begin
        i_0_reg_208 <= i_reg_546;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_0_reg_208 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln10_fu_461_p2 == 1'd1) & (icmp_ln22_fu_445_p2 == 1'd0))) begin
        q_0_i_reg_219 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        q_0_i_reg_219 <= q_reg_563;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_rand_state_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_rand_state_o_ap_vld == 1'b1)))) begin
        rand_state <= grp_ma_unitdatax_request_fu_344_rand_state_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_rand_state_o_ap_vld == 1'b1))) begin
        rand_state <= grp_phy_txend_confirm_fu_292_rand_state_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_rand_state_o_ap_vld == 1'b1))) begin
        rand_state <= grp_initial_edca_process_fu_240_rand_state_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_read_pointer_be_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_read_pointer_be_o_ap_vld == 1'b1)))) begin
        read_pointer_be <= grp_ma_unitdatax_request_fu_344_read_pointer_be_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_read_pointer_be_o_ap_vld == 1'b1))) begin
        read_pointer_be <= grp_phy_txend_confirm_fu_292_read_pointer_be_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_read_pointer_be_o_ap_vld == 1'b1))) begin
        read_pointer_be <= grp_initial_edca_process_fu_240_read_pointer_be_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_read_pointer_bk_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_read_pointer_bk_o_ap_vld == 1'b1)))) begin
        read_pointer_bk <= grp_ma_unitdatax_request_fu_344_read_pointer_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_read_pointer_bk_o_ap_vld == 1'b1))) begin
        read_pointer_bk <= grp_phy_txend_confirm_fu_292_read_pointer_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_read_pointer_bk_o_ap_vld == 1'b1))) begin
        read_pointer_bk <= grp_initial_edca_process_fu_240_read_pointer_bk_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_read_pointer_vi_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_read_pointer_vi_o_ap_vld == 1'b1)))) begin
        read_pointer_vi <= grp_ma_unitdatax_request_fu_344_read_pointer_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_read_pointer_vi_o_ap_vld == 1'b1))) begin
        read_pointer_vi <= grp_phy_txend_confirm_fu_292_read_pointer_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_read_pointer_vi_o_ap_vld == 1'b1))) begin
        read_pointer_vi <= grp_initial_edca_process_fu_240_read_pointer_vi_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_read_pointer_vo_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_read_pointer_vo_o_ap_vld == 1'b1)))) begin
        read_pointer_vo <= grp_ma_unitdatax_request_fu_344_read_pointer_vo_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_read_pointer_vo_o_ap_vld == 1'b1))) begin
        read_pointer_vo <= grp_phy_txend_confirm_fu_292_read_pointer_vo_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_read_pointer_vo_o_ap_vld == 1'b1))) begin
        read_pointer_vo <= grp_initial_edca_process_fu_240_read_pointer_vo_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_vi_backoff_counter_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_vi_backoff_counter_ap_vld == 1'b1)))) begin
        vi_backoff_counter <= grp_ma_unitdatax_request_fu_344_vi_backoff_counter;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_vi_backoff_counter_o_ap_vld == 1'b1))) begin
        vi_backoff_counter <= grp_phy_txend_confirm_fu_292_vi_backoff_counter_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_vi_backoff_counter_o_ap_vld == 1'b1))) begin
        vi_backoff_counter <= grp_initial_edca_process_fu_240_vi_backoff_counter_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_vo_backoff_counter_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_vo_backoff_counter_ap_vld == 1'b1)))) begin
        vo_backoff_counter <= grp_ma_unitdatax_request_fu_344_vo_backoff_counter;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_vo_backoff_counter_o_ap_vld == 1'b1))) begin
        vo_backoff_counter <= grp_phy_txend_confirm_fu_292_vo_backoff_counter_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_vo_backoff_counter_o_ap_vld == 1'b1))) begin
        vo_backoff_counter <= grp_initial_edca_process_fu_240_vo_backoff_counter_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_write_pointer_be_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_write_pointer_be_o_ap_vld == 1'b1)))) begin
        write_pointer_be <= grp_ma_unitdatax_request_fu_344_write_pointer_be_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_write_pointer_be_o_ap_vld == 1'b1))) begin
        write_pointer_be <= grp_phy_txend_confirm_fu_292_write_pointer_be_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_write_pointer_be_o_ap_vld == 1'b1))) begin
        write_pointer_be <= grp_initial_edca_process_fu_240_write_pointer_be_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_write_pointer_bk_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_write_pointer_bk_o_ap_vld == 1'b1)))) begin
        write_pointer_bk <= grp_ma_unitdatax_request_fu_344_write_pointer_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_write_pointer_bk_o_ap_vld == 1'b1))) begin
        write_pointer_bk <= grp_phy_txend_confirm_fu_292_write_pointer_bk_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_write_pointer_bk_o_ap_vld == 1'b1))) begin
        write_pointer_bk <= grp_initial_edca_process_fu_240_write_pointer_bk_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_write_pointer_vi_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_write_pointer_vi_o_ap_vld == 1'b1)))) begin
        write_pointer_vi <= grp_ma_unitdatax_request_fu_344_write_pointer_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_write_pointer_vi_o_ap_vld == 1'b1))) begin
        write_pointer_vi <= grp_phy_txend_confirm_fu_292_write_pointer_vi_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_write_pointer_vi_o_ap_vld == 1'b1))) begin
        write_pointer_vi <= grp_initial_edca_process_fu_240_write_pointer_vi_o;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_ma_unitdatax_request_fu_344_write_pointer_vo_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_ma_unitdatax_request_fu_344_write_pointer_vo_o_ap_vld == 1'b1)))) begin
        write_pointer_vo <= grp_ma_unitdatax_request_fu_344_write_pointer_vo_o;
    end else if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_write_pointer_vo_o_ap_vld == 1'b1))) begin
        write_pointer_vo <= grp_phy_txend_confirm_fu_292_write_pointer_vo_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_write_pointer_vo_o_ap_vld == 1'b1))) begin
        write_pointer_vo <= grp_initial_edca_process_fu_240_write_pointer_vo_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln11_fu_467_p2 == 1'd1) | (icmp_ln10_reg_556 == 1'd0)))) begin
        add_ln15_reg_578 <= add_ln15_fu_484_p2;
        icmp_ln16_reg_584 <= icmp_ln16_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13))) begin
        count <= ap_phi_mux_count_new_0_i_phi_fu_233_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln22_fu_445_p2 == 1'd0))) begin
        count_load_reg_551 <= count;
        icmp_ln10_reg_556 <= icmp_ln10_fu_461_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        data_1_fu_132 <= mac_frame_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_reg_546 <= i_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln10_reg_556 == 1'd1))) begin
        q_reg_563 <= q_fu_473_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln10_reg_556 == 1'd1) & (icmp_ln11_fu_467_p2 == 1'd0))) begin
        zext_ln12_reg_568[6 : 0] <= zext_ln12_fu_479_p1[6 : 0];
    end
end

always @ (*) begin
    if (((grp_phy_txend_confirm_fu_292_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((icmp_ln16_reg_584 == 1'd0)) begin
            ap_phi_mux_count_new_0_i_phi_fu_233_p4 = add_ln15_reg_578;
        end else if ((icmp_ln16_reg_584 == 1'd1)) begin
            ap_phi_mux_count_new_0_i_phi_fu_233_p4 = 7'd0;
        end else begin
            ap_phi_mux_count_new_0_i_phi_fu_233_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_count_new_0_i_phi_fu_233_p4 = 'bx;
    end
end

always @ (*) begin
    if (((grp_phy_txend_confirm_fu_292_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13) & (icmp_ln16_reg_584 == 1'd1))) begin
        call_ln17_phy_txend_request_fu_429_ap_start = 1'b1;
    end else begin
        call_ln17_phy_txend_request_fu_429_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (grp_phy_txend_confirm_fu_292_current_txop_holder_o_ap_vld == 1'b1))) begin
        current_txop_holder_o = grp_phy_txend_confirm_fu_292_current_txop_holder_o;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_initial_edca_process_fu_240_current_txop_holder_o_ap_vld == 1'b1))) begin
        current_txop_holder_o = grp_initial_edca_process_fu_240_current_txop_holder_o;
    end else begin
        current_txop_holder_o = current_txop_holder_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        current_txop_holder_o_ap_vld = grp_phy_txend_confirm_fu_292_current_txop_holder_o_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        current_txop_holder_o_ap_vld = grp_initial_edca_process_fu_240_current_txop_holder_o_ap_vld;
    end else begin
        current_txop_holder_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        data_ce0 = grp_ma_unitdatax_request_fu_344_data_ce0;
    end else begin
        data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        edca_queues_address0 = grp_ma_unitdatax_request_fu_344_edca_queues_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        edca_queues_address0 = grp_phy_txend_confirm_fu_292_edca_queues_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        edca_queues_address0 = grp_initial_edca_process_fu_240_edca_queues_address0;
    end else begin
        edca_queues_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        edca_queues_ce0 = grp_ma_unitdatax_request_fu_344_edca_queues_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        edca_queues_ce0 = grp_phy_txend_confirm_fu_292_edca_queues_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        edca_queues_ce0 = grp_initial_edca_process_fu_240_edca_queues_ce0;
    end else begin
        edca_queues_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        edca_queues_d0 = grp_ma_unitdatax_request_fu_344_edca_queues_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        edca_queues_d0 = grp_phy_txend_confirm_fu_292_edca_queues_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        edca_queues_d0 = grp_initial_edca_process_fu_240_edca_queues_d0;
    end else begin
        edca_queues_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        edca_queues_we0 = grp_ma_unitdatax_request_fu_344_edca_queues_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        edca_queues_we0 = grp_phy_txend_confirm_fu_292_edca_queues_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        edca_queues_we0 = grp_initial_edca_process_fu_240_edca_queues_we0;
    end else begin
        edca_queues_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        frame_address0 = zext_ln12_reg_568;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln16_reg_584 == 1'd0))) begin
        frame_address0 = grp_phy_data_request_fu_422_data_address0;
    end else begin
        frame_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        frame_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln16_reg_584 == 1'd0))) begin
        frame_ce0 = grp_phy_data_request_fu_422_data_ce0;
    end else begin
        frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        frame_we0 = 1'b1;
    end else begin
        frame_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mac_frame_address0 = zext_ln12_fu_479_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mac_frame_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        mac_frame_address0 = grp_phy_txend_confirm_fu_292_frame_to_transfer_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        mac_frame_address0 = grp_initial_edca_process_fu_240_frame_to_transfer_address0;
    end else begin
        mac_frame_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7))) begin
        mac_frame_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        mac_frame_ce0 = grp_phy_txend_confirm_fu_292_frame_to_transfer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        mac_frame_ce0 = grp_initial_edca_process_fu_240_frame_to_transfer_ce0;
    end else begin
        mac_frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        mac_frame_d0 = grp_phy_txend_confirm_fu_292_frame_to_transfer_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        mac_frame_d0 = grp_initial_edca_process_fu_240_frame_to_transfer_d0;
    end else begin
        mac_frame_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        mac_frame_we0 = grp_phy_txend_confirm_fu_292_frame_to_transfer_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        mac_frame_we0 = grp_initial_edca_process_fu_240_frame_to_transfer_we0;
    end else begin
        mac_frame_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        source_addr_mac_ce0 = grp_ma_unitdatax_request_fu_344_source_addr_mac_ce0;
    end else begin
        source_addr_mac_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        source_addr_mac_ce1 = grp_ma_unitdatax_request_fu_344_source_addr_mac_ce1;
    end else begin
        source_addr_mac_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_ma_unitdatax_request_fu_344_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_ma_unitdatax_request_fu_344_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_initial_edca_process_fu_240_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln22_fu_445_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln11_fu_467_p2 == 1'd1) | (icmp_ln10_reg_556 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((grp_phy_txend_confirm_fu_292_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_484_p2 = (count_load_reg_551 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state13_on_subcall_done = ((grp_phy_data_request_fu_422_ap_done == 1'b0) & (icmp_ln16_reg_584 == 1'd0));
end

assign data_address0 = grp_ma_unitdatax_request_fu_344_data_address0;

assign dest_addr_mac_address0 = 3'd0;

assign dest_addr_mac_address1 = 3'd0;

assign dest_addr_mac_ce0 = 1'b0;

assign dest_addr_mac_ce1 = 1'b0;

assign dest_addr_mac_d0 = 8'd0;

assign dest_addr_mac_d1 = 8'd0;

assign dest_addr_mac_we0 = 1'b0;

assign dest_addr_mac_we1 = 1'b0;

assign grp_initial_edca_process_fu_240_ap_start = grp_initial_edca_process_fu_240_ap_start_reg;

assign grp_ma_unitdatax_request_fu_344_ap_start = grp_ma_unitdatax_request_fu_344_ap_start_reg;

assign grp_phy_data_request_fu_422_ap_start = grp_phy_data_request_fu_422_ap_start_reg;

assign grp_phy_txend_confirm_fu_292_ap_start = grp_phy_txend_confirm_fu_292_ap_start_reg;

assign i_fu_451_p2 = (i_0_reg_208 + 7'd1);

assign icmp_ln10_fu_461_p2 = ((count == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_467_p2 = ((q_0_i_reg_219 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_490_p2 = ((add_ln15_fu_484_p2 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_445_p2 = ((i_0_reg_208 == 7'd100) ? 1'b1 : 1'b0);

assign q_fu_473_p2 = (q_0_i_reg_219 + 7'd1);

assign received_frame_address0 = 7'd0;

assign received_frame_address1 = 7'd0;

assign received_frame_ce0 = 1'b0;

assign received_frame_ce1 = 1'b0;

assign received_frame_d0 = 8'd0;

assign received_frame_d1 = 8'd0;

assign received_frame_we0 = 1'b0;

assign received_frame_we1 = 1'b0;

assign source_addr_mac_address0 = grp_ma_unitdatax_request_fu_344_source_addr_mac_address0;

assign source_addr_mac_address1 = grp_ma_unitdatax_request_fu_344_source_addr_mac_address1;

assign zext_ln12_fu_479_p1 = q_0_i_reg_219;

always @ (posedge ap_clk) begin
    zext_ln12_reg_568[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //send_frame
